export const testAction = {
  TEST_REQUEST: 'TEST_REQUEST',
  TEST_SUCCESS: 'TEST_SUCCESS',
  TEST_FAILURE: 'TEST_FAILURE',
};

export const CoinMarketCapAction = {
  GET_LISTING_LATEST_REQUEST: 'GET_LISTING_LATEST_REQUEST',
  GET_LISTING_LATEST_SUCCESS: 'GET_LISTING_LATEST_SUCCESS',
  GET_LISTING_LATEST_FAILURE: 'GET_LISTING_LATEST_FAILURE',
}
